R = 10;
I = 0:1:10;
V = R.*I;
P = R*I.^2;
disp([I ; V ; P]);
plot(I, V, 'g', I, P, 'b');
xlabel('Dòng điện (A)');
ylabel('Hiệu điện thế và công suất');
title('Đồ thị hiệu điện thế và công suất theo định luật Ohm');
legend('Hiệu điện thế', 'Công suất');